# Use a lightweight Python image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy everything from your project folder
COPY edge-face-recognition/ ./edge-face-recognition/

# Set working directory to where your Python code lives
WORKDIR /app/edge-face-recognition

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to run your app
CMD ["python", "main.py"]